export const FIND_COURSES_SUCCESS = "FIND_COURSES_SUCCESS";
export const FIND_COURSES_FAILURE = "FIND_COURSES_FAILURE";

export const FIND_SPECIFIC_COURSE_SUCCESS = "FIND_SPECIFIC_COURSE_SUCCESS";
export const FIND_SPECIFIC_COURSE_FAILURE = "FIND_SPECIFIC_COURSE_FAILURE";

export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";

export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAILURE = "EDIT_COURSE_FAILURE";

export const TOGGLE_STATUS_COURSE_SUCCESS = "TOGGLE_STATUS_COURSE_SUCCESS";
export const TOGGLE_STATUS_COURSE_FAILURE = "TOGGLE_STATUS_COURSE_FAILURE";
