export const FIND_FEEDBACK_SUCCESS = "FIND_FEEDBACK_SUCCESS";
export const FIND_FEEDBACK_FAILURE = "FIND_FEEDBACK_FAILURE";

export const ADD_NEW_FEEDBACK_SUCCESS = "ADD_FEEDBACK_SUCCESS";
export const ADD_NEW_FEEDBACK_FAILURE = "ADD_FEEDBACK_FAILURE";

export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_FAILURE = "DELETE_FEEDBACK_FAILURE";

export const UPDATE_FEEDBACK_SUCCESS = "UPDATE_FEEDBACK_SUCCESS";
export const UPDATE_FEEDBACK_FAILURE = "UPDATE_FEEDBACK_FAILURE";