export const FIND_RESOURCES_SUCCESS = "FIND_RESOURCES_SUCCESS";
export const FIND_RESOURCES_FAILURE = "FIND_RESOURCES_FAILURE";

export const ADD_NEW_RESOURCE_SUCCESS = "ADD_NEW_RESOURCE_SUCCESS"; 
export const ADD_NEW_RESOURCE_FAILURE = "ADD_NEW_RESOURCE_FAILURE";

export const UPDATE_RESOURCE_SUCCESS = "UPDATE_RESOURCE_SUCCESS";
export const UPDATE_RESOURCE_FAILURE = "UPDATE_RESOURCE_FAILURE";

export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAILURE = "DELETE_RESOURCE_FAILURE";
