// success cases
export const FIND_STUDENTS_SUCCESS = "FIND_STUDENTS_SUCCESS"; // CASE FIND ALL STUDENTS - SUCCESS
export const ADD_NEW_STUDENT = "ADD_NEW_STUDENT"; // CASE CREATE STUDENT - SUCCESS
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS"; // CASE EDIT STUDENT - SUCCESS
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"; // CASE DELETE STUDENT - SUCCESS

// fail cases
export const FIND_STUDENTS_FAILURE = "FIND_STUDENTS_FAILURE";
export const ADD_NEW_STUDENT_FAILURE = "ADD_NEW_STUDENT_FAILURE";
export const EDIT_STUDENT_FAILURE = "EDIT_STUDENT_FAILURE";
export const DELETE_STUDENT_FAILURE = "DELETE_STUDENT_FAILURE";
