// Exports for Get Method
export const FIND_TRAINERS_SUCCESS = "FIND_TRAINERS_SUCCESS";
export const FIND_TRAINERS_FAILURE = "FIND_TRAINERS_FAILURE";

// Exports for Post Method
export const ADD_NEW_TRAINER_SUCCESS = "ADD_NEW_TRAINER_SUCCESS";
export const ADD_NEW_TRAINER_FAILURE = "ADD_NEW_TRAINER_FAILURE";

// Exports for Edit Method
export const EDIT_NEW_TRAINER_SUCCESS = "EDIT_NEW_TRAINER_SUCCESS";
export const EDIT_NEW_TRAINER_FAILURE = "EDIT_NEW_TRAINER_SUCCESS";

//Exports for Delete Method
export const DELETE_TRAINER_SUCCESS = "DELETE_TRAINER_SUCCESS";
export const DELETE_TRAINER_FAILURE = "DELETE_TRAINER_FAILURE";
